### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SandraMadarnas** [4GeeksAcademy/Raul-Gimenez-Form#1]
Feedback de Sandra:

¡Raúl, estás muy cerca de lograrlo! Solo hay un pequeño detalle que no podemos pasar por alto. Necesitas asegurarte de que los campos de entrada "Card" y "CVC" no acepten texto y tengan una longitud máxima de 16 y 3 caracteres respectivamente.

Este ajuste es importante para garantizar la correcta entrada de datos y mejorar la usabilidad del formulario.

Recuerda que estoy aquí para ayudarte en lo que necesites. No dudes en consultarme si tienes alguna duda o requieres asistencia. ¡Ánimo, ya casi lo has conseguido!

-----------------------------------------------------------------------------------------------------------------------

Feedback Adrián:

Buen trabajo, pero necesitaría algunos cambios:

Los campos no son responsive. Lo idóneo sería que en mobile ocuparan el 100% de la pantalla, o como mínimo el 50% si el campo es muy pequeño
Faltan validaciones en los input card, cvc, amount, first-name, city, credit-card, last-name, select (aquí convendría repensar el name y id para sustituirlo por algo más específico, tipo “state” o “province”), postal-code y message
Falta el atributo name en los input card, cvc, first-name, city y message

**Comment by agarzon48** [comment]
Muy buen trabajo!
